export const fontFileMap = {
  "BreeSerif": "BreeSerif.otf",
  "Cucho Bold": "Cucho Bold.otf",
  "Cucho": "Cucho Bold.otf",
  "Fz Thư pháp Tiểu tự Fontzin": "Fz Thư pháp Tiểu tự Fontzin.ttf",
  "Fz Thư pháp Đại tự Fontzin": "Fz Thư pháp Đại tự Fontzin.ttf",
  "Gotham Medium": "Gotham-Medium.otf",
  "Gotham Thin": "Gotham-Thin.otf",
  "Gotham Ultra": "Gotham-Ultra.otf",
  "HP DNS Gibsons One Bold": "HP DNS Gibsons One Bold.otf",
  "HP DNS Gibsons One Outline": "HP DNS Gibsons One Outline.ttf",
  "HP DNS Gibsons One Semi Bold": "HP DNS Gibsons One Semi Bold.otf",
  "HP DNS Gibsons One": "HP DNS Gibsons One Bold.otf",
  "HP Monstice Base": "HP Monstice Base.otf",
  "HP Monstice Emboss": "HP Monstice Emboss.otf",
  "HP Monstice Engraved": "HP Monstice Engraved.otf",
  "HP Monstice Inline": "HP Monstice Inline.otf",
  "iCiel Alina": "iCiel Alina.otf",
  "iCiel Altus Serif": "iCiel Altus Serif.otf",
  "iCiel Altus": "iCiel Altus Extra.otf",
  "iciel Cadena": "iciel Cadena.ttf",
  "iCiel Crocante": "iCiel Crocante.otf",
  "iCiel Finch bold": "iCiel Finch bold.otf",
  "iCiel Finch": "iCiel Finch bold.otf",
  "iCiel Kermel": "iCiel Kermel.otf",
  "iCiel Pacifico": "iCiel Pacifico.otf",
  "iCiel Rukola": "iCiel Rukola.otf",
  "iCiel TALUHLA": "iCiel TALUHLA.otf",
  "iCielAmerigraf": "iCielAmerigraf.otf",
  "iCielBambola": "iCielBambola.otf",
  "iCielCadena": "iciel Cadena.ttf",
  "iCielParisSerif Bold": "iCielParisSerif-Bold.otf",
  "iCielSoupofJustice": "iCielSoupofJustice.otf",
  "KD Moon Light": "KD-Moon-Light.ttf",
  "Mijas Ultra": "Mijas-Ultra.otf",
  "MTD 1613 Basilius": "MTD 1613 Basilius.otf",
  "MTD 21 Cent": "MTD 21 Cent.otf",
  "MTD Aaleyah Thick Stamp": "MTD Aaleyah Thick Stamp.otf",
  "MTD Abbassy Script": "MTD Abbassy Script.otf",
  "MTD Acryle Script": "MTD Acryle Script.otf",
  "MTD Addictype": "MTD Addictype.otf",
  "MTD Adventures Unlimited Sans": "MTD Adventures Unlimited Sans.otf",
  "MTD Adventures Unlimited Script Bold": "MTD Adventures Unlimited Script Bold.otf",
  "MTD Adventures Unlimited Script": "MTD Adventures Unlimited Script Bold.otf",
  "MTD Afecta": "MTD Afecta.otf",
  "MTD Alexandria": "MTD Alexandria Ornaments.otf",
  "MTD AlFresco": "MTD AlFresco.otf",
  "MTD Amarone": "MTD Amarone.otf",
  "MTD Ampihan": "MTD Ampihan.otf",
  "MTD Amstrong": "MTD Amstrong Ornament.ttf",
  "MTD Andrade Pro Script": "MTD Andrade Pro Script.otf",
  "MTD Antro Vectra": "MTD Antro Vectra.otf",
  "MTD Anydore": "MTD Anydore.otf",
  "MTD Ariestha": "MTD Ariestha.otf",
  "MTD Arthington": "MTD Arthington.otf",
  "MTD Artisan": "MTD Artisan Ornament.otf",
  "MTD Attention Script": "MTD Attention Script.otf",
  "MTD Auckland Script": "MTD Auckland Script.otf",
  "MTD Australian Script": "MTD Australian Script.otf",
  "MTD Authemart": "MTD Authemart Extras.ttf",
  "MTD Authentica Rough": "MTD Authentica Rough.otf",
  "MTD Auto Quick": "MTD Auto Quick.otf",
  "MTD Autogate Stamp": "MTD Autogate Stamp.otf",
  "MTD Ave Utan": "MTD Ave Utan.otf",
  "MTD Avelina": "MTD Avelina.otf",
  "MTD Babylonica ROB": "MTD Babylonica ROB.otf",
  "MTD Balerno Bold": "MTD Balerno Bold.otf",
  "MTD Balerno Light": "MTD Balerno Light.otf",
  "MTD Balerno Regular": "MTD Balerno Regular.otf",
  "MTD Barakah Regular": "MTD Barakah Regular.otf",
  "MTD Bell Martellus": "MTD Bell Martellus.ttf",
  "MTD Bella Rose Alternates": "MTD Bella Rose Alternates.otf",
  "MTD Bella Rose Plain": "MTD Bella Rose Plain.otf",
  "MTD Bella Rose": "MTD Bella Rose Alternates.otf",
  "MTD Benton": "MTD Benton.otf",
  "MTD Berliana Monoline": "MTD Berliana Monoline Swash.ttf",
  "MTD Berrigela Anitta": "MTD Berrigela Anitta.otf",
  "MTD Bertolessi": "MTD Bertolessi.otf",
  "MTD Bhaltazar": "MTD Bhaltazar.otf",
  "MTD Bigilla Bold": "MTD Bigilla Bold.otf",
  "MTD Bigilla": "MTD Bigilla Bold.otf",
  "MTD Black and Shadow Font": "MTD Black and Shadow Font.otf",
  "MTD Black Baron Gothic": "MTD Black Baron Gothic.otf",
  "MTD Black Night": "MTD Black Night.otf",
  "MTD Blaze Glory": "MTD Blaze Glory.otf",
  "MTD Blaze Glory Ornament": "MTD Blaze _ Glory Ornament.ttf",
  "MTD Blaze Glory Ornaments Drop": "MTD Blaze _ Glory Ornaments Drop.ttf",
  "MTD Blue Island Std": "MTD Blue Island Std.otf",
  "MTD Brand Pro Inline": "MTD Brand Pro Inline.otf",
  "MTD Brand Pro Light": "MTD Brand Pro Light.otf",
  "MTD Brand Pro Shade": "MTD Brand Pro Shade.otf",
  "MTD Brand Pro": "MTD Brand Pro Inline.otf",
  "MTD Brignola PUA Script": "MTD Brignola PUA Script.otf",
  "MTD Briliants Typeface": "MTD Briliants Typeface.otf",
  "MTD Broadway Script Rough": "MTD Broadway Script Rough.otf",
  "MTD Broadway Script": "MTD Broadway Script Rough.otf",
  "MTD Brunette": "MTD Brunette.otf",
  "MTD Bubble": "MTD Bubble.otf",
  "MTD Buffied": "MTD Buffied.otf",
  "MTD Bunga SVG": "MTD Bunga SVG.otf",
  "MTD Bunga": "MTD Bunga SVG.otf",
  "MTD Caerphilly Regular": "MTD Caerphilly Regular.otf",
  "MTD Candyland": "MTD Candyland.otf",
  "MTD Capellina Script": "MTD Capellina Script.otf",
  "MTD Carrington": "MTD Carrington.otf",
  "MTD Casanova Script EF Pro": "MTD Casanova Script EF Pro.otf",
  "MTD Chalmers": "MTD Chalmers.otf",
  "MTD Charlize One": "MTD Charlize One.otf",
  "MTD Cheese Sauce": "MTD Cheese Sauce.otf",
  "MTD Chuck Noon Script": "MTD Chuck Noon Script.otf",
  "MTD Cindo Kato": "MTD Cindo Kato.otf",
  "MTD City Stencil": "MTD City Stencil.otf",
  "MTD Clarkson Script Regular": "MTD Clarkson Script Regular.otf",
  "MTD Coffee Break Script 2": "MTD Coffee Break Script 2.otf",
  "MTD CS Delirian Script": "MTD CS Delirian Script.otf",
  "MTD CS Solange": "MTD CS Solange.otf",
  "MTD Danielle Harris Caps": "MTD Danielle Harris Caps.otf",
  "MTD Dartangnon ITC": "MTD Dartangnon ITC.otf",
  "MTD Daytonia": "MTD Daytonia.otf",
  "MTD Doppelganger Display": "MTD Doppelganger Display.otf",
  "MTD Douglass Pen": "MTD Douglass Pen.otf",
  "MTD Ecstasy TTW": "MTD Ecstasy TTW.otf",
  "MTD Elipses Alt": "MTD Elipses Alt.otf",
  "MTD Elipses Bold Alt": "MTD Elipses Bold Alt.otf",
  "MTD Elipses Bold": "MTD Elipses Bold Alt.otf",
  "MTD Elipses Caps": "MTD Elipses Caps.otf",
  "MTD Elipses Italic Alt": "MTD Elipses Italic Alt.otf",
  "MTD Elipses Italic": "MTD Elipses Italic Alt.otf",
  "MTD Elipses": "MTD Elipses Alt.otf",
  "MTD Elodie": "MTD Elodie.otf",
  "MTD Esther": "MTD Esther.otf",
  "MTD Explorers": "MTD Explorers.otf",
  "MTD Fabulous Script": "MTD Fabulous Script.otf",
  "MTD Familia Script": "MTD Familia Script.otf",
  "MTD Fancy Melody": "MTD Fancy Melody.otf",
  "MTD Fashion Vogue": "MTD Fashion Vogue.otf",
  "MTD Feather": "MTD Feather.otf",
  "MTD Feliz En Vista Alternative": "MTD Feliz En Vista Alternative.otf",
  "MTD Feliz en Vista": "MTD Feliz En Vista Alternative.otf",
  "MTD Fiftyes": "MTD Fiftyes.otf",
  "MTD Fleurie": "MTD Fleurie.otf",
  "MTD Francesca": "MTD Francesca.otf",
  "MTD Fun Play Day": "MTD Fun Play Day.otf",
  "MTD Gambit Nouveau SG OT Std": "MTD Gambit Nouveau SG OT Std.otf",
  "MTD Genia": "MTD Genia.otf",
  "MTD Geraldyne": "MTD Geraldyne.otf",
  "MTD Gilroy Light Italic": "MTD Gilroy Light Italic.ttf",
  "MTD Gilroy Light": "MTD Gilroy Light Italic.ttf",
  "MTD Gilroy Medium Italic": "MTD Gilroy Medium Italic.ttf",
  "MTD Gilroy Medium": "MTD Gilroy Medium Italic.ttf",
  "MTD Gilroy Regular Italic": "MTD Gilroy Regular Italic.ttf",
  "MTD Gilroy Regular": "MTD Gilroy Regular Italic.ttf",
  "MTD Gilroy UltraLight Italic": "MTD Gilroy UltraLight Italic.ttf",
  "MTD Gilroy UltraLight": "MTD Gilroy UltraLight Italic.ttf",
  "MTD Girasol Shine": "MTD Girasol Shine.otf",
  "MTD Girasol": "MTD Girasol Shine.otf",
  "MTD Girly Things Regular": "MTD Girly Things Regular.otf",
  "MTD GoatskinBrush PersonalUse": "MTD GoatskinBrush_PersonalUse.otf",
  "MTD Gogoia Deco": "MTD Gogoia Deco.ttf",
  "MTD Good Day": "MTD Good Day.otf",
  "MTD Goodwater Brush": "MTD Goodwater Brush.otf",
  "MTD Goodwater Print Brush": "MTD Goodwater Print Brush.otf",
  "MTD Goodwater Print Sans 1": "MTD Goodwater Print Sans 1.otf",
  "MTD Goodwater Print Script 1": "MTD Goodwater Print Script 1.otf",
  "MTD Goodwater Sans 2": "MTD Goodwater Sans 2.otf",
  "MTD Goodwater Script 1": "MTD Goodwater Script 1.otf",
  "MTD Gorni": "MTD Gorni.otf",
  "MTD Grange": "MTD Grange.otf",
  "MTD Great Vibes": "MTD Great Vibes.otf",
  "MTD Great Victorian Swashed": "MTD Great Victorian Swashed.otf",
  "MTD Greatlove": "MTD Greatlove.otf",
  "MTD Greature": "MTD Greature.otf",
  "MTD Habibe": "MTD Habibe.otf",
  "MTD Hangbird": "MTD Hangbird.otf",
  "MTD Hard Stones Pro Rough": "MTD Hard Stones Pro Rough.otf",
  "MTD Hard Stones Pro Strip": "MTD Hard Stones Pro Strip.otf",
  "MTD Hard Stones Pro": "MTD Hard Stones Pro Rough.otf",
  "MTD Harukaze Slant": "MTD Harukaze Slant.otf",
  "MTD Harukaze Solid": "MTD Harukaze Solid.otf",
  "MTD Harukaze": "MTD Harukaze Slant.otf",
  "MTD Hayne Script Clean": "MTD Hayne Script Clean.otf",
  "MTD Hello Paris Serif": "MTD Hello Paris Serif.otf",
  "MTD Hey August": "MTD Hey August.otf",
  "MTD High Way": "MTD High Way.otf",
  "MTD Hillstown Aged": "MTD Hillstown Aged.otf",
  "MTD Hillstown Clean": "MTD Hillstown Clean.otf",
  "MTD Himalaya Sans Serif": "MTD Himalaya Sans Serif.otf",
  "MTD Himalaya": "MTD Himalaya Sans Serif.otf",
  "MTD Hipster Script": "MTD Hipster Script.otf",
  "MTD Houstoner Script": "MTD Houstoner Script.otf",
  "MTD Hu Kou": "MTD Hu Kou.otf",
  "MTD Hummingbird": "MTD Hummingbird.otf",
  "MTD Hummington": "MTD Hummington.otf",
  "MTD Jailetter": "MTD Jailetter.otf",
  "MTD JRS": "MTD JRS.otf",
  "MTD JV Signature Regular": "MTD JV Signature Regular.ttf",
  "MTD Karolin": "MTD Karolin Swash.otf",
  "MTD Katherine Script": "MTD Katherine Script.otf",
  "MTD Katheryna": "MTD Katheryna Swashes.otf",
  "MTD Kawoszeh": "MTD Kawoszeh.otf",
  "MTD King Edward Basic Inline Italic": "MTD King Edward Basic Inline Italic.otf",
  "MTD King Edward Basic Inline": "MTD King Edward Basic Inline Italic.otf",
  "MTD King Edward Basic Italic": "MTD King Edward Basic Italic.otf",
  "MTD King Edward Basic Shadow": "MTD King Edward Basic Shadow.otf",
  "MTD King Edward Basic": "MTD King Edward Basic Inline Italic.otf",
  "MTD King Edward Shadow": "MTD King Edward Shadow.otf",
  "MTD King Edward": "MTD King Edward Basic Inline Italic.otf",
  "MTD Kiramba": "MTD Kiramba.otf",
  "MTD Kosova": "MTD Kosova.otf",
  "MTD Lastone": "MTD Lastone.otf",
  "MTD Lazy Ride Script": "MTD Lazy Ride Script.otf",
  "MTD LeJardin Floral": "MTD LeJardin Floral.otf",
  "MTD Letra Pro Headline": "MTD Letra Pro Headline.otf",
  "MTD Levitee": "MTD Levitee.ttf",
  "MTD Love": "MTD Love.otf",
  "MTD Loveletter No.9": "MTD Loveletter No.9.otf",
  "MTD Loveya Script": "MTD Loveya Script.otf",
  "MTD Madame Cosmetics": "MTD Madame Cosmetics.otf",
  "MTD Magnies": "MTD Magnies.otf",
  "MTD Maryatha": "MTD Maryatha.otf",
  "MTD Matsury": "MTD Matsury.otf",
  "MTD Mavera": "MTD Mavera.otf",
  "MTD Megrim": "MTD Megrim.otf",
  "MTD Middle Saxony Text": "MTD Middle Saxony Text.otf",
  "MTD Midnight Tales": "MTD Midnight Tales.otf",
  "MTD Milkstore 01 Script Textured": "MTD Milkstore 01 Script Textured.otf",
  "MTD Milkstore 06 Textured": "MTD Milkstore 06 Textured.otf",
  "MTD Mind Blowing Light": "MTD Mind Blowing Light.otf",
  "MTD MitreSquare": "MTD MitreSquare.otf",
  "MTD MK Broken Types": "MTD MK Broken Types.otf",
  "MTD Monopola Script": "MTD Monopola Script.otf",
  "MTD MusashiBB": "MTD MusashiBB.otf",
  "MTD Nettizen Script Dancing": "MTD Nettizen Script Dancing.otf",
  "MTD New Year s Story": "MTD New Year_s Story.otf",
  "MTD Oceania": "MTD Oceania.otf",
  "MTD Old Finlander": "MTD Old Finlander.otf",
  "MTD One Starry Night": "MTD One Starry Night.otf",
  "MTD Oops": "MTD Oops.otf",
  "MTD Orangimelo": "MTD Orangimelo.otf",
  "MTD Othelie Line": "MTD Othelie Line.otf",
  "MTD Othelie": "MTD Othelie Line.otf",
  "MTD Owah Tagu Siam NF": "MTD Owah Tagu Siam NF.otf",
  "MTD P22 Ruthie": "MTD P22 Ruthie.otf",
  "MTD Palomino Sans One": "MTD Palomino Sans One.otf",
  "MTD Palomino Sans Two": "MTD Palomino Sans Two.otf",
  "MTD Palomino Script": "MTD Palomino Script.otf",
  "MTD Parnas": "MTD Parnas.otf",
  "MTD PF DaVinci Script Pro Inked": "MTD PF DaVinci Script Pro Inked.otf",
  "MTD PF DaVinci Script Pro": "MTD PF DaVinci Script Pro Inked.otf",
  "MTD PN Macabre Millionaire": "MTD PN Macabre Millionaire.otf",
  "MTD Portrait Script Bounce": "MTD Portrait Script Bounce.ttf",
  "MTD Prida 01 Black": "MTD Prida 01 Black.otf",
  "MTD Prida 01 Bold": "MTD Prida 01 Bold.otf",
  "MTD Prida 01 Light": "MTD Prida 01 Light.otf",
  "MTD Prida 01": "MTD Prida 01 Black.otf",
  "MTD Prida 02 Calt": "MTD Prida 02 Calt.otf",
  "MTD QuangNinh Thuphap 1": "MTD QuangNinh_Thuphap_1.ttf",
  "MTD QuangNinh Thuphap 2": "MTD QuangNinh_Thuphap_2.otf",
  "MTD Quaver": "MTD Quaver.otf",
  "MTD Queen Victoria Inine Swash": "MTD Queen Victoria Inine Swash.otf",
  "MTD Queen Victoria Inline": "MTD Queen Victoria Inline.otf",
  "MTD Queen Victoria Outline": "MTD Queen Victoria Outline.otf",
  "MTD Queen Victoria Shadow": "MTD Queen Victoria Shadow.otf",
  "MTD Queen Victoria Swash": "MTD Queen Victoria Swash.otf",
  "MTD Queen Victoria Vintage": "MTD Queen Victoria Vintage.otf",
  "MTD Queen Victoria": "MTD Queen Victoria Inine Swash.otf",
  "MTD Quimbly Bold": "MTD Quimbly Bold.otf",
  "MTD Quimbly Light": "MTD Quimbly Light.otf",
  "MTD Quimbly": "MTD Quimbly Bold.otf",
  "MTD Ramblin Paint": "MTD Ramblin Paint.otf",
  "MTD Ranthing": "MTD Ranthing.otf",
  "MTD Red Bright Swash": "MTD Red Bright Swash.otf",
  "MTD Red Bright": "MTD Red Bright Swash.otf",
  "MTD Renaissance Garden Italic": "MTD Renaissance Garden Italic.otf",
  "MTD Retrology Block": "MTD Retrology Block.otf",
  "MTD Rockyeah Brush": "MTD Rockyeah Brush.otf",
  "MTD Romance Fatal Serif Pro": "MTD Romance Fatal Serif Pro.otf",
  "MTD Rose Petals Two": "MTD Rose Petals Two.ttf",
  "MTD Rosemary Signature": "MTD Rosemary Signature.otf",
  "MTD Rossegenia": "MTD Rossegenia.otf",
  "MTD Roughish": "MTD Roughish.otf",
  "MTD Royal Touch": "MTD Royal Touch.otf",
  "MTD Sailing Heart Solid": "MTD Sailing Heart Solid.otf",
  "MTD Sailing Heart": "MTD Sailing Heart Solid.otf",
  "MTD Santiago": "MTD Santiago.otf",
  "MTD Santos Dumont": "MTD Santos Dumont.otf",
  "MTD Scripture": "MTD Scripture.otf",
  "MTD Second Lyrics": "MTD Second Lyrics.otf",
  "MTD Selva": "MTD Selva.otf",
  "MTD Serenity Script": "MTD Serenity Script.otf",
  "MTD Shalima": "MTD Shalima.otf",
  "MTD Shapely": "MTD Shapely.otf",
  "MTD ShimesOne": "MTD ShimesOne.otf",
  "MTD Shodo Gothic": "MTD Shodo Gothic.otf",
  "MTD Shopping Script": "MTD Shopping Script.otf",
  "MTD Silver Crown": "MTD Silver Crown.otf",
  "MTD Simpletune": "MTD Simpletune.otf",
  "MTD Sirunian": "MTD Sirunian.otf",
  "MTD Skylar": "MTD Skylar.otf",
  "MTD Snow For Santa": "MTD Snow For Santa.otf",
  "MTD Sofye": "MTD Sofye.ttf",
  "MTD SouthPacific": "MTD SouthPacific.otf",
  "MTD Spagheti Script": "MTD Spagheti Script.otf",
  "MTD Spooksville": "MTD Spooksville.otf",
  "MTD Spring Chicken": "MTD Spring Chicken.otf",
  "MTD SpringVibes Floral Light": "MTD SpringVibes Floral Light.otf",
  "MTD SpringVibes Floral": "MTD SpringVibes Floral Light.otf",
  "MTD SpringVibes": "MTD SpringVibes Floral Light.otf",
  "MTD St Friska": "MTD St Friska.otf",
  "MTD Stanley Stamp": "MTD Stanley Stamp.otf",
  "MTD Stanley": "MTD Stanley Stamp.otf",
  "MTD Stanwood": "MTD Stanwood.otf",
  "MTD Starcity Script": "MTD Starcity Script.otf",
  "MTD Stash Vintage Light": "MTD Stash Vintage Light.otf",
  "MTD Stash Vintage": "MTD Stash Vintage Light.otf",
  "MTD Streetwear": "MTD Streetwear.otf",
  "MTD Summer Show": "MTD Summer Show.otf",
  "MTD Thank You So Much": "MTD Thank You So Much.otf",
  "MTD The Beauty Blink": "MTD The Beauty Blink.otf",
  "MTD The Beautyline": "MTD The Beautyline.otf",
  "MTD The Duality": "MTD The Duality.otf",
  "MTD The Hotelio": "MTD The Hotelio.otf",
  "MTD The Moon Falls": "MTD The Moon Falls.otf",
  "MTD Thirsk": "MTD Thirsk.otf",
  "MTD Tita Script Alt": "MTD Tita Script Alt.otf",
  "MTD Traditian": "MTD Traditian.otf",
  "MTD Troyline Script": "MTD Troyline Script.otf",
  "MTD Twas The Night Before Christmas": "MTD Twas The Night Before Christmas.otf",
  "MTD Ultimus": "MTD Ultimus Ornaments.otf",
  "MTD Unicorn Calligraphy": "MTD Unicorn Calligraphy.otf",
  "MTD UT Sugar Cane": "MTD UT Sugar Cane.otf",
  "MTD Valky Bold": "MTD Valky Bold.otf",
  "MTD Valky Light": "MTD Valky Light.otf",
  "MTD Valky Regular": "MTD Valky Regular.otf",
  "MTD Valky Semibold": "MTD Valky Semibold.otf",
  "MTD Verona Lotte": "MTD Verona Lotte.otf",
  "MTD Volloa": "MTD Volloa.otf",
  "MTD Voyage Bold": "MTD Voyage Bold.otf",
  "MTD Voyage Regular": "MTD Voyage Regular.otf",
  "MTD VVD Golden Horn Lined": "MTD VVD Golden Horn Lined.otf",
  "MTD VVD Golden Horn Pressed": "MTD VVD Golden Horn Pressed.otf",
  "MTD VVD Golden Horn Roughen": "MTD VVD Golden Horn Roughen.otf",
  "MTD VVD Golden Horn Shadow": "MTD VVD Golden Horn Shadow.otf",
  "MTD VVD Golden Horn": "MTD VVD Golden Horn Lined.otf",
  "MTD Wanita": "MTD Wanita.otf",
  "MTD WetSpring": "MTD WetSpring.ttf",
  "MTD Whittier": "MTD Whittier.otf",
  "MTD William Letter": "MTD William Letter.otf",
  "MTD Woolen": "MTD Woolen.otf",
  "MTD Xuong Rong 01": "MTD Xuong Rong 01.otf",
  "MTD Yerington": "MTD Yerington.otf",
  "MTD Yessy": "MTD Yessy.otf",
  "MTD Yolanda Princess": "MTD Yolanda Princess.otf",
  "MTD Youther Script": "MTD Youther Script.otf",
  "MTD Yozakura JP Light": "MTD Yozakura JP Light.otf",
  "MTD Yozakura JP": "MTD Yozakura JP Light.otf",
  "MyriadPro Regular": "MyriadPro-Regular.otf",
  "Nabila": "Nabila.ttf",
  "OrtisanSignature": "OrtisanSignature.ttf",
  "OS Shiipt": "OS-Shiipt.otf",
  "Pony": "Pony.ttf",
  "scripti": "scripti.ttf",
  "SDC Waliglona": "SDC -Waliglona.otf",
  "SDC Betalisa": "SDC Betalisa.otf",
  "SDC Evitrian": "SDC Evitrian.otf",
  "SDC House": "SDC House.otf",
  "SDC Jhode": "SDC Jhode.otf",
  "SDC Sign Rathi": "SDC Sign Rathi.otf",
  "SDC The Handwritten Watermark": "SDC The Handwritten Watermark.otf",
  "SDC Aaript": "SDC-Aaript.otf",
  "SDC Abrace": "SDC-Abrace.otf",
  "SDC Agolar": "SDC-Agolar.otf",
  "SDC Agolic": "SDC-Agolic.otf",
  "SDC Aguack": "SDC-Aguack.otf",
  "SDC Agular": "SDC-Agular.otf",
  "SDC Aguold": "SDC-Aguold.otf",
  "SDC Aleght": "SDC-Aleght.otf",
  "SDC Alelar (2)": "SDC-Alelar (2).otf",
  "SDC Alelic (3)": "SDC-Alelic (3).otf",
  "SDC Alelic": "SDC-Alelic (3).otf",
  "SDC Aleold (2)": "SDC-Aleold (2).otf",
  "SDC Aleold.221207 1051": "SDC-Aleold.221207-1051.otf",
  "SDC Aleold": "SDC-Aleold (2).otf",
  "SDC Allipt": "SDC-Allipt.otf",
  "SDC Allist": "SDC-Allist.otf",
  "SDC Ameats": "SDC-Ameats.otf",
  "SDC Ameype": "SDC-Ameype.otf",
  "SDC Ameyst": "SDC-Ameyst.otf",
  "SDC Amsdam": "SDC-Amsdam.otf",
  "SDC Amslar": "SDC-Amslar.otf",
  "SDC Anasia": "SDC-Anasia.otf",
  "SDC Angely": "SDC-Angely.otf",
  "SDC Angife": "SDC-Angife.otf",
  "SDC Anthem": "SDC-Anthem.otf",
  "SDC Apoius": "SDC-Apoius.otf",
  "SDC Arc897": "SDC-Arc897.otf",
  "SDC ARCpSDC": "SDC-ARCpSDC.otf",
  "SDC Arctes": "SDC-Arctes.otf",
  "SDC Arslon": "SDC-Arslon.otf",
  "SDC Artuty": "SDC-Artuty.otf",
  "SDC Aslrry": "SDC-Aslrry.otf",
  "SDC Astout": "SDC-Astout.otf",
  "SDC Athene": "SDC-Athene.otf",
  "SDC Audrey": "SDC-Audrey.otf",
  "SDC Avaipt": "SDC-Avaipt.otf",
  "SDC Avence": "SDC-Avence.otf",
  "SDC Babtar": "SDC-Babtar.otf",
  "SDC Balace": "SDC-Balace.otf",
  "SDC Baleer": "SDC-Baleer.otf",
  "SDC Balipt": "SDC-Balipt.otf",
  "SDC Bango": "SDC-Bango.otf",
  "SDC Banins": "SDC-Banins.otf",
  "SDC Baript": "SDC-Baript.otf",
  "SDC Barrif": "SDC-Barrif.otf",
  "SDC BaSDCek": "SDC-BaSDCek.otf",
  "SDC Batate": "SDC-Batate.otf",
  "SDC Beaans": "SDC-Beaans.otf",
  "SDC Beaipt": "SDC-Beaipt.otf",
  "SDC Beaood": "SDC-Beaood.otf",
  "SDC Beaord": "SDC-Beaord.otf",
  "SDC Beatok": "SDC-Beatok.otf",
  "SDC Bebace": "SDC-Bebace.otf",
  "SDC BeCool": "SDC-BeCool.otf",
  "SDC Belers": "SDC-Belers.otf",
  "SDC Bellico": "SDC-Bellico.otf",
  "SDC Belved": "SDC-Belved.otf",
  "SDC Besach": "SDC-Besach.otf",
  "SDC Biging": "SDC-Biging.otf",
  "SDC Bilold": "SDC-Bilold.otf",
  "SDC Bisipt": "SDC-Bisipt.otf",
  "SDC Bjola": "SDC-Bjola.otf",
  "SDC BLAAWK": "SDC-BLAAWK.otf",
  "SDC Blahid": "SDC-Blahid.otf",
  "SDC Blaill": "SDC-Blaill.otf",
  "SDC Blaond": "SDC-Blaond.otf",
  "SDC Blauff": "SDC-Blauff.otf",
  "SDC Bloipt": "SDC-Bloipt.otf",
  "SDC Bloush": "SDC-Bloush.otf",
  "SDC Blyofs": "SDC-Blyofs.otf",
  "SDC Bonage": "SDC-Bonage.otf",
  "SDC Bonour": "SDC-Bonour.otf",
  "SDC Bouher": "SDC-Bouher.otf",
  "SDC Bouipt": "SDC-Bouipt.otf",
  "SDC Bradow": "SDC-Bradow.otf",
  "SDC Braga": "SDC-Braga.otf",
  "SDC Briold": "SDC-Briold.otf",
  "SDC Brotch": "SDC-Brotch.otf",
  "SDC Brript": "SDC-Brript.otf",
  "SDC Bruipt": "SDC-Bruipt.otf",
  "SDC Brutte": "SDC-Brutte.otf",
  "SDC Bubont": "SDC-Bubont.otf",
  "SDC Buiton": "SDC-Buiton.otf",
  "SDC Bulary": "SDC-Bulary.otf",
  "SDC Calama": "SDC-Calama.otf",
  "SDC Calipt": "SDC-Calipt.otf",
  "SDC Canipt": "SDC-Canipt.otf",
  "SDC Canpee": "SDC-Canpee.otf",
  "SDC Capipt": "SDC-Capipt.otf",
  "SDC Carerg": "SDC-Carerg.otf",
  "SDC Carola": "SDC-Carola.otf",
  "SDC Carsta": "SDC-Carsta.otf",
  "SDC Carwer": "SDC-Carwer.otf",
  "SDC Caving": "SDC-Caving.otf",
  "SDC Chalest": "SDC-Chalest.otf",
  "SDC Cherga": "SDC-Cherga.otf",
  "SDC Chioup": "SDC-Chioup.otf",
  "SDC Chirie": "SDC-Chirie.otf",
  "SDC Choipt": "SDC-Choipt.otf",
  "SDC Cinake": "SDC-Cinake.otf",
  "SDC Cintra": "SDC-Cintra.otf",
  "SDC Clania": "SDC-Clania.otf",
  "SDC Cleine": "SDC-Cleine.otf",
  "SDC Cloice": "SDC-Cloice.otf",
  "SDC Coco FY": "SDC-Coco FY.otf",
  "SDC Codrux": "SDC-Codrux.otf",
  "SDC Condot": "SDC-Condot.otf",
  "SDC Conreu": "SDC-Conreu.otf",
  "SDC Consent": "SDC-Consent.otf",
  "SDC Cooilk": "SDC-Cooilk.otf",
  "SDC Corcan": "SDC-Corcan.otf",
  "SDC Corded": "SDC-Corded (2).otf",
  "SDC Corish": "SDC-Corish.otf",
  "SDC Corlar": "SDC-Corlar.otf",
  "SDC Cotuse": "SDC-Cotuse.otf",
  "SDC Cupake": "SDC-Cupake.otf",
  "SDC Cyrano": "SDC-Cyrano.otf",
  "SDC DaiLau": "SDC-DaiLau.otf",
  "SDC Darton": "SDC-Darton.otf",
  "SDC Dayand": "SDC-Dayand.otf",
  "SDC Days": "SDC-Days.otf",
  "SDC Deaane": "SDC-Deaane.otf",
  "SDC Deaipt": "SDC-Deaipt.otf",
  "SDC Delsto": "SDC-Delsto.otf",
  "SDC Dentra": "SDC-Dentra.otf",
  "SDC Desipt": "SDC-Desipt.otf",
  "SDC Desire": "SDC-Desire.otf",
  "SDC Desyrel": "SDC-Desyrel.otf",
  "SDC Detans": "SDC-Detans.otf",
  "SDC DHFush": "SDC-DHFush.otf",
  "SDC DHrush": "SDC-DHrush.otf",
  "SDC Diablo": "SDC-Diablo.otf",
  "SDC Diaond": "SDC-Diaond.otf",
  "SDC Digalis": "SDC-Digalis.otf",
  "SDC DKCard": "SDC-DKCard.otf",
  "SDC Domque": "SDC-Domque.otf",
  "SDC Doodly": "SDC-Doodly.otf",
  "SDC Dopipt": "SDC-Dopipt.otf",
  "SDC Dowver": "SDC-Dowver.otf",
  "SDC Duming": "SDC-Duming.otf",
  "SDC Egript": "SDC-Egript.otf",
  "SDC Elley": "SDC-Elley.otf",
  "SDC Endord": "SDC-Endord.otf",
  "SDC Endrow": "SDC-Endrow.otf",
  "SDC Engine": "SDC-Engine.otf",
  "SDC Erimig": "SDC-Erimig.otf",
  "SDC EsmPro": "SDC-EsmPro.otf",
  "SDC Eupnic": "SDC-Eupnic.otf",
  "SDC Eveeen": "SDC-Eveeen.otf",
  "SDC Eveght": "SDC-Eveght.otf",
  "SDC Fadlla": "SDC-Fadlla.otf",
  "SDC Fashion": "SDC-Fashion.otf",
  "SDC Feling": "SDC-Feling.otf",
  "SDC Ferlar": "SDC-Ferlar.otf",
  "SDC FjaOne": "SDC-FjaOne.otf",
  "SDC Flaipt": "SDC-Flaipt.otf",
  "SDC Fonine": "SDC-Fonine.otf",
  "SDC Forlly": "SDC-Forlly.otf",
  "SDC Foular": "SDC-Foular.otf",
  "SDC Fouold": "SDC-Fouold.otf",
  "SDC Freipt": "SDC-Freipt.otf",
  "SDC Freude": "SDC-Freude.otf",
  "SDC Freyle": "SDC-Freyle.otf",
  "SDC Galern": "SDC-Galern.otf",
  "SDC Ganree": "SDC-Ganree.otf",
  "SDC Gariny": "SDC-Gariny.otf",
  "SDC GenPro": "SDC-GenPro.otf",
  "SDC Geoipt": "SDC-Geoipt.otf",
  "SDC Giaza": "SDC-Giaza.otf",
  "SDC Ginger": "SDC-Ginger.otf",
  "SDC Glojah": "SDC-Glojah.otf",
  "SDC Golaps": "SDC-Golaps.otf",
  "SDC Golipt": "SDC-Golipt.otf",
  "SDC Golype": "SDC-Golype.otf",
  "SDC Graamo": "SDC-Graamo.otf",
  "SDC Gracia": "SDC-Gracia.otf",
  "SDC Grahez": "SDC-Grahez.otf",
  "SDC Graitel": "SDC-Graitel.otf",
  "SDC Gralay 2": "SDC-Gralay 2.otf",
  "SDC Gralay": "SDC-Gralay 2.otf",
  "SDC Gralic": "SDC-Gralic.otf",
  "SDC Graman": "SDC-Graman.otf",
  "SDC Groded": "SDC-Groded.otf",
  "SDC Guella": "SDC-Guella.otf",
  "SDC Gumley": "SDC-Gumley.otf",
  "SDC Haming": "SDC-Haming.otf",
  "SDC Handlar": "SDC-Handlar.otf",
  "SDC Hanold": "SDC-Hanold.otf",
  "SDC HanPro": "SDC-HanPro.otf",
  "SDC HanTwo": "SDC-HanTwo.otf",
  "SDC Hapipt": "SDC-Hapipt.otf",
  "SDC Harony": "SDC-Harony.otf",
  "SDC Harpt": "SDC-Harpt.otf",
  "SDC Havart": "SDC-Havart 2.otf",
  "SDC Heaeen": "SDC-Heaeen.otf",
  "SDC Heaner": "SDC-Heaner.otf",
  "SDC Heanly": "SDC-Heanly.otf",
  "SDC Heaoth": "SDC-Heaoth.otf",
  "SDC Heaoul": "SDC-Heaoul.otf",
  "SDC Heimer": "SDC-Heimer.otf",
  "SDC Helcky": "SDC-Helcky.otf",
  "SDC Helets": "SDC-Helets.otf",
  "SDC Helga": "SDC-Helga.otf",
  "SDC Heline (2)": "SDC-Heline (2).otf",
  "SDC Heline": "SDC-Heline (2).otf",
  "SDC HelInk": "SDC-HelInk.otf",
  "SDC Helker": "SDC-Helker.otf",
  "SDC Herine": "SDC-Herine.otf",
  "SDC HerPro": "SDC-HerPro.otf",
  "SDC Hirake": "SDC-Hirake.otf",
  "SDC Hogfish": "SDC-Hogfish.otf",
  "SDC Holday": "SDC-Holday.otf",
  "SDC Holkes": "SDC-Holkes.otf",
  "SDC HolPro": "SDC-HolPro.otf",
  "SDC Hopsed": "SDC-Hopsed.otf",
  "SDC Hotsta": "SDC-Hotsta.otf",
  "SDC Houure": "SDC-Houure.otf",
  "SDC Hughs": "SDC-Hughs.otf",
  "SDC Ilyas": "SDC-Ilyas.otf",
  "SDC Indie": "SDC-Indie.otf",
  "SDC Intade": "SDC-Intade.otf",
  "SDC Intase": "SDC-Intase.otf",
  "SDC Iolthe": "SDC-Iolthe.otf",
  "SDC Janten": "SDC-Janten.otf",
  "SDC Jantus": "SDC-Jantus.otf",
  "SDC Jeaous": "SDC-Jeaous.otf",
  "SDC Jonipt": "SDC-Jonipt.otf",
  "SDC Journey": "SDC-Journey.otf",
  "SDC Jusday": "SDC-Jusday.otf",
  "SDC Jusing": "SDC-Jusing.otf",
  "SDC Justgue": "SDC-Justgue.otf",
  "SDC Karlita": "SDC-Karlita.otf",
  "SDC Karsha": "SDC-Karsha.otf",
  "SDC Kasush": "SDC-Kasush.otf",
  "SDC Kelso": "SDC-Kelso.otf",
  "SDC Kintom": "SDC-Kintom.otf",
  "SDC Kitten": "SDC-Kitten.otf",
  "SDC Koma": "SDC-Koma.otf",
  "SDC Konras": "SDC-Konras.otf",
  "SDC KorpSDC": "SDC-KorpSDC.otf",
  "SDC LaPoma": "SDC-LaPoma.otf",
  "SDC Larded": "SDC-Larded.otf",
  "SDC Lasise": "SDC-Lasise.otf",
  "SDC LeBNew": "SDC-LeBNew.otf",
  "SDC Lemday": "SDC-Lemday.otf",
  "SDC LeMure": "SDC-LeMure.otf",
  "SDC LeOsler": "SDC-LeOsler.otf",
  "SDC Lifans": "SDC-Lifans.otf",
  "SDC Lifipt": "SDC-Lifipt.otf",
  "SDC Lifsic": "SDC-Lifsic.otf",
  "SDC Lolack": "SDC-Lolack.otf",
  "SDC Lonide": "SDC-Lonide.otf",
  "SDC Lostar": "SDC-Lostar.otf",
  "SDC Lovion": "SDC-Lovion.otf",
  "SDC Lovure": "SDC-Lovure.otf",
  "SDC Ludous": "SDC-Ludous.otf",
  "SDC Lusipt": "SDC-Lusipt.otf",
  "SDC Mablla": "SDC-Mablla.otf",
  "SDC Madipt": "SDC-Madipt.otf",
  "SDC Magent": "SDC-Magent.otf",
  "SDC Manark": "SDC-Manark.otf",
  "SDC Manrry": "SDC-Manrry.otf",
  "SDC Maplla": "SDC-Maplla.otf",
  "SDC Marino": "SDC-Marino.otf",
  "SDC Marpro (2)": "SDC-Marpro (2).otf",
  "SDC MarPro": "SDC-Marpro (2).otf",
  "SDC Marres": "SDC-Marres.otf",
  "SDC Marujo": "SDC-Marujo.otf",
  "SDC Mauipt": "SDC-Mauipt.otf",
  "SDC Megnte": "SDC-Megnte.otf",
  "SDC Merria": "SDC-Merria.otf",
  "SDC Merular": "SDC-Merular.otf",
  "SDC Micine": "SDC-Micine.otf",
  "SDC Milams": "SDC-Milams.otf",
  "SDC Modety": "SDC-Modety.otf",
  "SDC Momnto": "SDC-Momnto.otf",
  "SDC Moname": "SDC-Moname.otf",
  "SDC Moorth": "SDC-Moorth.otf",
  "SDC Mosshi": "SDC-Mosshi.otf",
  "SDC Motica": "SDC-Motica.otf",
  "SDC Mukdua": "SDC-Mukdua.otf",
  "SDC Naiold": "SDC-Naiold.otf",
  "SDC Nauica": "SDC-Nauica.otf",
  "SDC Neuace": "SDC-Neuace.otf",
  "SDC NewM54": "SDC-NewM54.otf",
  "SDC Nexack": "SDC-Nexack.otf",
  "SDC Nexded": "SDC-Nexded.otf",
  "SDC Nexdow": "SDC-Nexdow.otf",
  "SDC Nexipt": "SDC-Nexipt.otf",
  "SDC Nicipt": "SDC-Nicipt.otf",
  "SDC Nigent": "SDC-Nigent.otf",
  "SDC Norold": "SDC-Norold.otf",
  "SDC Norular": "SDC-Norular.otf",
  "SDC Notera": "SDC-Notera.otf",
  "SDC Noting": "SDC-Noting.otf",
  "SDC Notold": "SDC-Notold.otf",
  "SDC Novlia": "SDC-Novlia.otf",
  "SDC Nubya": "SDC-Nubya.otf",
  "SDC Nuit": "SDC-Nuit.otf",
  "SDC OneDay": "SDC-OneDay.otf",
  "SDC Orishu": "SDC-Orishu.otf",
  "SDC PalaLC": "SDC-PalaLC.otf",
  "SDC Palint": "SDC-Palint.otf",
  "SDC Palipt": "SDC-Palipt.otf",
  "SDC Palton": "SDC-Palton.otf",
  "SDC Parise": "SDC-Parise.otf",
  "SDC ParPro": "SDC-ParPro.otf",
  "SDC Pasnak": "SDC-Pasnak.otf",
  "SDC Passion": "SDC-Passion.otf",
  "SDC Patipt": "SDC-Patipt.otf",
  "SDC Pentic": "SDC-Pentic.otf",
  "SDC Peqack": "SDC-Peqack.otf",
  "SDC Peqlar": "SDC-Peqlar.otf",
  "SDC Pleent": "SDC-Pleent.otf",
  "SDC Posine": "SDC-Posine.otf",
  "SDC Progs": "SDC-Progs.otf",
  "SDC Pyeine": "SDC-Pyeine.otf",
  "SDC Qalrif": "SDC-Qalrif.otf",
  "SDC Qualar": "SDC-Qualar.otf",
  "SDC Quarzo": "SDC-Quarzo.otf",
  "SDC Radder": "SDC-Radder.otf",
  "SDC Rawone": "SDC-Rawone.otf",
  "SDC Redwns": "SDC-Redwns.otf",
  "SDC RekaCF": "SDC-RekaCF.otf",
  "SDC Rekipt": "SDC-Rekipt.otf",
  "SDC Ret000": "SDC-Ret000.otf",
  "SDC Ridlar": "SDC-Ridlar.otf",
  "SDC Ridold": "SDC-Ridold.otf",
  "SDC Rinena": "SDC-Rinena.otf",
  "SDC Rio016": "SDC-Rio016.otf",
  "SDC RisPro": "SDC-RisPro.otf",
  "SDC Roaage": "SDC-Roaage.otf",
  "SDC Roaush": "SDC-Roaush.otf",
  "SDC Rocess": "SDC-Rocess.otf",
  "SDC Rohtwo": "SDC-Rohtwo.otf",
  "SDC Rolury": "SDC-Rolury.otf",
  "SDC Romcho": "SDC-Romcho.otf",
  "SDC Rosipt": "SDC-Rosipt.otf",
  "SDC Rosnda": "SDC-Rosnda.otf",
  "SDC Rosore": "SDC-Rosore.otf",
  "SDC Ruca": "SDC-Ruca.otf",
  "SDC Rusick": "SDC-Rusick.otf",
  "SDC Rusour": "SDC-Rusour.otf",
  "SDC Sabper": "SDC-Sabper.otf",
  "SDC Safipt": "SDC-Safipt.otf",
  "SDC Sage 2": "SDC-Sage 2.otf",
  "SDC Sage": "SDC-Sage 2.otf",
  "SDC Saiica": "SDC-Saiica.otf",
  "SDC Salans": "SDC-Salans.otf",
  "SDC Salina": "SDC-Salina.otf",
  "SDC Salipt": "SDC-Salipt.otf",
  "SDC Sambay": "SDC-Sambay.otf",
  "SDC Santer": "SDC-Santer.otf",
  "SDC Santis": "SDC-Santis.otf",
  "SDC Sarifa": "SDC-Sarifa.otf",
  "SDC Saugar": "SDC-Saugar.otf",
  "SDC Sayeez": "SDC-Sayeez.otf",
  "SDC SecPro": "SDC-SecPro.otf",
  "SDC Seiton": "SDC-Seiton.otf",
  "SDC Serhin": "SDC-Serhin.otf",
  "SDC Serium": "SDC-Serium.otf",
  "SDC Sevana": "SDC-Sevana.otf",
  "SDC Shapen": "SDC-Shapen.otf",
  "SDC Shiaru": "SDC-Shiaru.otf",
  "SDC Shoans": "SDC-Shoans.otf",
  "SDC Sholab": "SDC-Sholab.otf",
  "SDC Sigipt": "SDC-Sigipt.otf",
  "SDC Silver": "SDC-Silver.otf",
  "SDC Skill": "SDC-Skill.otf",
  "SDC Slaush": "SDC-Slaush.otf",
  "SDC Sloack 2": "SDC-Sloack 2.otf",
  "SDC Sloack": "SDC-Sloack 2.otf",
  "SDC Smirk": "SDC-Smirk.otf",
  "SDC Snelipt": "SDC-Snelipt.otf",
  "SDC Sneold": "SDC-Sneold.otf",
  "SDC SpaAge": "SDC-SpaAge.otf",
  "SDC Spldor": "SDC-Spldor.otf",
  "SDC Stadly": "SDC-Stadly.otf",
  "SDC Steady": "SDC-Steady.otf",
  "SDC Stella": "SDC-Stella.otf",
  "SDC Steows": "SDC-Steows.otf",
  "SDC Stiaff": "SDC-Stiaff.otf",
  "SDC Stiing": "SDC-Stiing.otf",
  "SDC Stiray": "SDC-Stiray.otf",
  "SDC Stiund": "SDC-Stiund.otf",
  "SDC Stoans": "SDC-Stoans.otf",
  "SDC Storif": "SDC-Storif.otf",
  "SDC Strdas": "SDC-Strdas.otf",
  "SDC Strove": "SDC-Strove.otf",
  "SDC Stuush": "SDC-Stuush.otf",
  "SDC Suagie": "SDC-Suagie.otf",
  "SDC Sunday": "SDC-Sunday.otf",
  "SDC Sunine": "SDC-Sunine.otf",
  "SDC Sunora": "SDC-Sunora.otf",
  "SDC Sunower": "SDC-Sunower.otf",
  "SDC Supgic": "SDC-Supgic.otf",
  "SDC Swaton": "SDC-Swaton.otf",
  "SDC Swetie": "SDC-Swetie.otf",
  "SDC Swiium": "SDC-Swiium.otf",
  "SDC Swilar": "SDC-Swilar.otf",
  "SDC Takres": "SDC-Takres.otf",
  "SDC Tamdo": "SDC-Tamdo.otf",
  "SDC Tanans": "SDC-Tanans.otf",
  "SDC Tango": "SDC-Tango.otf",
  "SDC Tanine": "SDC-Tanine.otf",
  "SDC Tanipt": "SDC-Tanipt.otf",
  "SDC Teaers": "SDC-Teaers.otf",
  "SDC Theans": "SDC-Theans.otf",
  "SDC Theers": "SDC-Theers.otf",
  "SDC Theipt": "SDC-Theipt.otf",
  "SDC Thelar": "SDC-Thelar.otf",
  "SDC Theold": "SDC-Theold.otf",
  "SDC Theory": "SDC-Theory.otf",
  "SDC Theret": "SDC-Theret.otf",
  "SDC Tinipt": "SDC-Tinipt.otf",
  "SDC Tioans": "SDC-Tioans.otf",
  "SDC Tipper": "SDC-Tipper.otf",
  "SDC TokgPx": "SDC-TokgPx.otf",
  "SDC Topret": "SDC-Topret.otf",
  "SDC Toyans": "SDC-Toyans.otf",
  "SDC TraDark": "SDC-TraDark.otf",
  "SDC Trench": "SDC-Trench.otf",
  "SDC TruPro": "SDC-TruPro.otf",
  "SDC Twiipt": "SDC-Twiipt.otf",
  "SDC UncBen": "SDC-UncBen.otf",
  "SDC UnTift": "SDC-UnTift.otf",
  "SDC UTTess": "SDC-UTTess.otf",
  "SDC UTTlar": "SDC-UTTlar.otf",
  "SDC Vala": "SDC-Vala.otf",
  "SDC Vamres": "SDC-Vamres.otf",
  "SDC Vanlla": "SDC-Vanlla.otf",
  "SDC VanPro": "SDC-VanPro.otf",
  "SDC Velies": "SDC-Velies.otf",
  "SDC Veneer": "SDC-Veneer.otf",
  "SDC Verine": "SDC-Verine.otf",
  "SDC Verrry": "SDC-Verrry.otf",
  "SDC Vicria": "SDC-Vicria.otf",
  "SDC Walows": "SDC-Walows.otf",
  "SDC Walton": "SDC-Walton.otf",
  "SDC Watlar.221213 1707": "SDC-Watlar.221213-1707.otf",
  "SDC Watlar": "SDC-Watlar.221213-1707.otf",
  "SDC Watold": "SDC-Watold.otf",
  "SDC Wedday": "SDC-Wedday.otf",
  "SDC Welont": "SDC-Welont.otf",
  "SDC Wendi": "SDC-Wendi.otf",
  "SDC WeYuth": "SDC-WeYuth.otf",
  "SDC Wooker": "SDC-Wooker.otf",
  "SDC Wrisno": "SDC-Wrisno.otf",
  "SDC Wrount": "SDC-Wrount.otf",
  "SDC Wylgen": "SDC-Wylgen.otf",
  "SDC XXIipt": "SDC-XXIipt.otf",
  "SDC Yamasi": "SDC-Yamasi.otf",
  "SDC Yipes": "SDC-Yipes.otf",
  "SDC Youove": "SDC-Youove.otf",
  "SDC Zaiipt": "SDC-Zaiipt.otf",
  "SDC Zatyan": "SDC-Zatyan.otf",
  "SDC Zicets": "SDC-Zicets.otf",
  "SVN Aaron Script": "SVN-Aaron Script.otf",
  "SVN Abril Fatface": "SVN-Abril Fatface.ttf",
  "SVN Adeline": "SVN-Adeline.ttf",
  "SVN Agoka Italic": "SVN-Agoka-Italic.otf",
  "SVN Agoka Regular": "SVN-Agoka-Regular.otf",
  "SVN Aguda Black": "SVN-Aguda Black.otf",
  "SVN Aguda Bold": "SVN-Aguda Bold.otf",
  "SVN Aguda Light": "SVN-Aguda Light.otf",
  "SVN Aguda Regular": "SVN-Aguda Regular.otf",
  "SVN Alek Bold": "SVN-Alek Bold.otf",
  "SVN Alek Regular": "SVN-Alek Regular.otf",
  "SVN Aleo Bold Italic": "SVN-Aleo Bold Italic.otf",
  "SVN Aleo Bold": "SVN-Aleo Bold Italic.otf",
  "SVN Aleo Italic": "SVN-Aleo Italic.otf",
  "SVN Aleo Light Italic": "SVN-Aleo Light Italic.otf",
  "SVN Aleo Light": "SVN-Aleo Light Italic.otf",
  "SVN Aleo Regular": "SVN-Aleo Regular.otf",
  "SVN Allea Script": "SVN-Allea Script.ttf",
  "SVN Allogist": "SVN-Allogist.otf",
  "SVN Amethyst Dingbats": "SVN-Amethyst Dingbats.otf",
  "SVN Amethyst TrueType": "SVN-Amethyst TrueType.ttf",
  "SVN Amethyst": "SVN-Amethyst Dingbats.otf",
  "SVN Ameyallinda Signature": "SVN-Ameyallinda Signature.otf",
  "SVN Amsdam": "SVN-Amsdam.ttf",
  "SVN Amstirdam": "SVN-Amstirdam.otf",
  "SVN Anastasia": "SVN-Anastasia.ttf",
  "SVN Angellife": "SVN-Angellife.ttf",
  "SVN Angely": "SVN-Angely Extras.ttf",
  "SVN Anthem": "SVN-Anthem.otf",
  "SVN Apollonius": "SVN-Apollonius.otf",
  "SVN Archaic 1897": "SVN-Archaic 1897.ttf",
  "SVN Archattes": "SVN-Archattes.otf",
  "SVN ARCO Typography": "SVN-ARCO Typography.otf",
  "SVN Arsilon": "SVN-Arsilon.otf",
  "SVN Artful Beauty": "SVN-Artful Beauty.ttf",
  "SVN Aslang Barry": "SVN-Aslang Barry.otf",
  "SVN Astronout": "SVN-Astronout.otf",
  "SVN Athene": "SVN-Athene.otf",
  "SVN Audrey": "SVN-Audrey.otf",
  "SVN Avaline Script": "SVN-Avaline Script.ttf",
  "SVN Avengeance": "SVN-Avengeance.otf",
  "SVN Baby Youre A Star": "SVN-Baby Youre A Star.otf",
  "SVN Bahud Aroyek": "SVN-Bahud Aroyek.otf",
  "SVN Bali Script": "SVN-Bali Script.ttf",
  "SVN Balladeer Light": "SVN-Balladeer Light.ttf",
  "SVN Ballarea Typeface": "SVN-Ballarea Typeface.otf",
  "SVN Banana Chip Muffins": "SVN-Banana Chip Muffins.otf",
  "SVN Bango": "SVN-Bango.otf",
  "SVN Barnyard Script": "SVN-Barnyard Script.otf",
  "SVN Barnyard Serif": "SVN-Barnyard Serif.otf",
  "SVN Batman Forever Alternate": "SVN-Batman Forever Alternate.otf",
  "SVN Be Cool": "SVN-Be Cool.otf",
  "SVN Beachwood Sans": "SVN-Beachwood Sans.otf",
  "SVN Beachwood Script": "SVN-Beachwood Script.otf",
  "SVN Beauford": "SVN-Beauford.otf",
  "SVN Beauty Atok Script": "SVN-Beauty Atok Script.ttf",
  "SVN Bebop Slab Face": "SVN-Bebop Slab Face.otf",
  "SVN Bellwethers": "SVN-Bellwethers.otf",
  "SVN Beloved": "SVN-Beloved.otf",
  "SVN Bestagrach": "SVN-Bestagrach.otf",
  "SVN Betalisa": "SVN-Betalisa.otf",
  "SVN Big Noodle Titling": "SVN-Big Noodle Titling.otf",
  "SVN Billy Bold": "SVN-Billy Bold.ttf",
  "SVN Bistro Script": "SVN-Bistro Script.otf",
  "SVN Black Diamond": "SVN-Black Diamond.ttf",
  "SVN Black Orchid": "SVN-Black Orchid.otf",
  "SVN Black Stuff Bold": "SVN-Black Stuff Bold.otf",
  "SVN BLACKHAWK": "SVN-BLACKHAWK Swash.otf",
  "SVN Bladekill": "SVN-Bladekill.otf",
  "SVN Blenda Script": "SVN-Blenda Script.ttf",
  "SVN Blog Script": "SVN-Blog Script.ttf",
  "SVN Blow Brush": "SVN-Blow Brush.ttf",
  "SVN Blywoofs": "SVN-Blywoofs.otf",
  "SVN Bonjour": "SVN-Bonjour.otf",
  "SVN BonVoyage Regular": "SVN-BonVoyage-Regular.otf",
  "SVN Bougher": "SVN-Bougher.otf",
  "SVN Boutique Script": "SVN-Boutique Script.ttf",
  "SVN Braga": "SVN-Braga.otf",
  "SVN Brandon Printed Shadow": "SVN-Brandon Printed Shadow.otf",
  "SVN Briko Bold": "SVN-Briko Bold.otf",
  "SVN Brownhill Script": "SVN-Brownhill Script.otf",
  "SVN Brunette": "SVN-Brunette.otf",
  "SVN Bruselo Script": "SVN-Bruselo Script Ornaments.otf",
  "SVN Bublont": "SVN-Bublont.otf",
  "SVN Buinton": "SVN-Buinton.otf",
  "SVN Bulgary": "SVN-Bulgary.otf",
  "SVN Calama": "SVN-Calama.otf",
  "SVN Callpedia Script": "SVN-Callpedia Script.otf",
  "SVN Candy Script": "SVN-Candy Script.otf",
  "SVN Canopee": "SVN-Canopee.otf",
  "SVN Caprica Script": "SVN-Caprica Script.ttf",
  "SVN Carista": "SVN-Carista.otf",
  "SVN Carlosberg": "SVN-Carlosberg.otf",
  "SVN Carola": "SVN-Carola.otf",
  "SVN Carrotflower": "SVN-Carrotflower.otf",
  "SVN Cavorting": "SVN-Cavorting.otf",
  "SVN Chalkboard The Best": "SVN-Chalkboard The Best.ttf",
  "SVN Cheeky Rabbit": "SVN-Cheeky Rabbit.ttf",
  "SVN Cheeseburga": "SVN-Cheeseburga.otf",
  "SVN Chicken Noodle Soup": "SVN-Chicken Noodle Soup.otf",
  "SVN Childish Reverie": "SVN-Childish Reverie Doodles.otf",
  "SVN Chopin Script": "SVN-Chopin Script.otf",
  "SVN Cinnamoncake": "SVN-Cinnamoncake.ttf",
  "SVN Cintra": "SVN-Cintra.otf",
  "SVN Claytonia": "SVN-Claytonia.otf",
  "SVN Clementine": "SVN-Clementine.otf",
  "SVN Clouds Caprice": "SVN-Clouds Caprice.otf",
  "SVN Coco FY": "SVN-Coco FY.ttf",
  "SVN Coder's Crux": "SVN-Coder's Crux.otf",
  "SVN Coder s Crux": "SVN-Coder's Crux.otf",
  "SVN Conqueror Didot": "SVN-Conqueror Didot.otf",
  "SVN Consent": "SVN-Consent.otf",
  "SVN Constreu": "SVN-Constreu.otf",
  "SVN Cookies And Milk": "SVN-Cookies And Milk.otf",
  "SVN Corki Regular": "SVN-Corki Regular.otf",
  "SVN Corki Rounded": "SVN-Corki Rounded.otf",
  "SVN Corki Tuscan Rounded": "SVN-Corki Tuscan Rounded.otf",
  "SVN Corki Tuscan": "SVN-Corki Tuscan Rounded.otf",
  "SVN Cornish": "SVN-Cornish.ttf",
  "SVN Cottage & Farmhouse": "SVN-Cottage & Farmhouse Dots.otf",
  "SVN Cupcake": "SVN-Cupcake.otf",
  "SVN Cyrano": "SVN-Cyrano.otf",
  "SVN Daisy Lau": "SVN-Daisy Lau.otf",
  "SVN Darleston": "SVN-Darleston.otf",
  "SVN Dayland": "SVN-Dayland.ttf",
  "SVN Days": "SVN-Days.otf",
  "SVN Deadhead Script": "SVN-Deadhead Script.ttf",
  "SVN Dear Jane": "SVN-Dear Jane.otf",
  "SVN Delabasto": "SVN-Delabasto.ttf",
  "SVN Dentra": "SVN-Dentra.otf",
  "SVN Desire": "SVN-Desire.otf",
  "SVN Dessert Menu Script": "SVN-Dessert Menu Script.ttf",
  "SVN Desyrel": "SVN-Desyrel.otf",
  "SVN Determination Sans": "SVN-Determination Sans.otf",
  "SVN DHF Dexsar Brush": "SVN-DHF Dexsar Brush.otf",
  "SVN DHF Harry's Brush": "SVN-DHF Harry's Brush.otf",
  "SVN Diablo": "SVN-Diablo.otf",
  "SVN Diamond": "SVN-Diamond.otf",
  "SVN Diamonda": "SVN-Diamonda.otf",
  "SVN Digitalis": "SVN-Digitalis.ttf",
  "SVN DK Clochard": "SVN-DK Clochard.otf",
  "SVN Dominique": "SVN-Dominique.otf",
  "SVN Doodly": "SVN-Doodly.ttf",
  "SVN Dope Script": "SVN-Dope Script.ttf",
  "SVN Down River": "SVN-Down River.otf",
  "SVN Dumpling": "SVN-Dumpling.otf",
  "SVN Egregio Script": "SVN-Egregio Script.ttf",
  "SVN Elley": "SVN-Elley.ttf",
  "SVN Endless Sorrow": "SVN-Endless Sorrow Catchword.otf",
  "SVN Engine": "SVN-Engine.otf",
  "SVN Erika Ormig": "SVN-Erika Ormig.otf",
  "SVN Esmeralda Pro": "SVN-Esmeralda Pro.otf",
  "SVN Euphorigenic": "SVN-Euphorigenic.otf",
  "SVN Evergreen": "SVN-Evergreen.otf",
  "SVN Every Movie Every Night": "SVN-Every Movie Every Night.ttf",
  "SVN Fadilla": "SVN-Fadilla.ttf",
  "SVN Fashion": "SVN-Fashion.otf",
  "SVN Felix Titling": "SVN-Felix Titling.otf",
  "SVN Fergana Regular": "SVN-Fergana-Regular.otf",
  "SVN Fjalla One": "SVN-Fjalla One.otf",
  "SVN Flamingo Script": "SVN-Flamingo Script.otf",
  "SVN Fontaine": "SVN-Fontaine.otf",
  "SVN Fords Folly": "SVN-Fords Folly.otf",
  "SVN Fourth Bold": "SVN-Fourth Bold.ttf",
  "SVN Fourth Extras": "SVN-Fourth Extras.ttf",
  "SVN Fourth Regular": "SVN-Fourth Regular.ttf",
  "SVN Freestyle": "SVN-Freestyle.otf",
  "SVN Fresh Script": "SVN-Fresh Script.otf",
  "SVN Freude": "SVN-Freude.otf",
  "SVN Friends Forever": "SVN-Friends Forever Extras.otf",
  "SVN Gallery Modern": "SVN-Gallery Modern.otf",
  "SVN Gang of Three": "SVN-Gang of Three.otf",
  "SVN Garleriny": "SVN-Garleriny.otf",
  "SVN Genica Pro": "SVN-Genica Pro.otf",
  "SVN Giaza": "SVN-Giaza.otf",
  "SVN Ginger": "SVN-Ginger.otf",
  "SVN Gloria Hallelujah": "SVN-Gloria Hallelujah.otf",
  "SVN Golden Youth Caps": "SVN-Golden Youth Caps.otf",
  "SVN Goldeye Type": "SVN-Goldeye Type.ttf",
  "SVN Gracia": "SVN-Gracia.otf",
  "SVN Grahamo": "SVN-Grahamo.otf",
  "SVN GrandSlang Italic": "SVN-GrandSlang-Italic.otf",
  "SVN GrandSlang Roman": "SVN-GrandSlang-Roman.otf",
  "SVN Graphitel": "SVN-Graphitel.otf",
  "SVN Gratelos Display 2": "SVN-Gratelos Display 2.otf",
  "SVN Gratelos Display": "SVN-Gratelos Display 2.otf",
  "SVN Gravhez": "SVN-Gravhez.otf",
  "SVN Grocery Rounded": "SVN-Grocery Rounded.ttf",
  "SVN Guerrilla": "SVN-Guerrilla.ttf",
  "SVN Gumley": "SVN-Gumley.otf",
  "SVN Hamstring": "SVN-Hamstring.otf",
  "SVN Hand Gothic Bold": "SVN-Hand Gothic Bold.otf",
  "SVN Hand Gothic Regular": "SVN-Hand Gothic Regular.otf",
  "SVN Hand Of Sean Pro": "SVN-Hand Of Sean Pro.otf",
  "SVN Handelson Two": "SVN-Handelson Two.otf",
  "SVN Haptic Script": "SVN-Haptic Script.otf",
  "SVN Harman Script": "SVN-Harman Script.ttf",
  "SVN Harmony": "SVN-Harmony.otf",
  "SVN Have Heart 2": "SVN-Have Heart 2.otf",
  "SVN Have Heart": "SVN-Have Heart 2.otf",
  "SVN HC 1785 GLC Baskerville": "SVN-HC 1785 GLC Baskerville.otf",
  "SVN HC Aerojones NF": "SVN-HC Aerojones NF.otf",
  "SVN HC Alterner": "SVN-HC Alterner.otf",
  "SVN HC Anas Rusty Typewriter": "SVN-HC Anas Rusty Typewriter.otf",
  "SVN HC Anchor Jack": "SVN-HC Anchor Jack.otf",
  "SVN HC Appareo Black Italic": "SVN-HC Appareo Black Italic.otf",
  "SVN HC Appareo Black": "SVN-HC Appareo Black Italic.otf",
  "SVN HC Bauhaus 93": "SVN-HC Bauhaus 93.otf",
  "SVN HC Belinda": "SVN-HC Belinda.otf",
  "SVN HC Bernard MT Cond": "SVN-HC Bernard MT Cond.otf",
  "SVN HC Bourbon Grotesque": "SVN-HC Bourbon Grotesque.otf",
  "SVN HC Braga Huis": "SVN-HC Braga Huis.otf",
  "SVN HC Broadway Cond": "SVN-HC Broadway Cond.otf",
  "SVN HC Built Titling": "SVN-HC Built Titling.otf",
  "SVN HC Calvous": "SVN-HC Calvous.otf",
  "SVN HC Carlson": "SVN-HC Carlson.otf",
  "SVN HC Carosello": "SVN-HC Carosello.otf",
  "SVN HC Colombo Sans": "SVN-HC Colombo Sans.otf",
  "SVN HC Cubano Sharp": "SVN-HC Cubano Sharp.otf",
  "SVN HC Cubano": "SVN-HC Cubano Sharp.otf",
  "SVN HC Culture": "SVN-HC Culture.otf",
  "SVN HC Cyrene": "SVN-HC Cyrene.otf",
  "SVN HC Deftone Stylus": "SVN-HC Deftone Stylus.otf",
  "SVN HC East Market": "SVN-HC East Market.otf",
  "SVN HC Ekim Mezunu": "SVN-HC Ekim Mezunu.otf",
  "SVN HC Elixir Circus": "SVN-HC Elixir Circus.otf",
  "SVN HC Elixir Sans": "SVN-HC Elixir Sans.otf",
  "SVN HC Explorer Condensed": "SVN-HC Explorer Condensed.otf",
  "SVN HC Gibsons One": "SVN-HC Gibsons One.otf",
  "SVN HC Gibsons Two": "SVN-HC Gibsons Two.otf",
  "SVN HC Gneisenauette": "SVN-HC Gneisenauette.otf",
  "SVN HC Gorod": "SVN-HC Gorod.otf",
  "SVN HC Green Grove": "SVN-HC Green Grove.otf",
  "SVN HC Grindstone Display": "SVN-HC Grindstone Display.otf",
  "SVN HC Haydon Brush": "SVN-HC Haydon Brush.otf",
  "SVN HC Impossibilium": "SVN-HC Impossibilium.otf",
  "SVN HC Jungle Adventurer": "SVN-HC Jungle Adventurer.otf",
  "SVN HC Just Old Fashion": "SVN-HC Just Old Fashion.otf",
  "SVN HC Kodiak": "SVN-HC Kodiak.otf",
  "SVN HC Lexington": "SVN-HC Lexington.otf",
  "SVN HC Marvin Visions": "SVN-HC Marvin Visions.otf",
  "SVN HC Matura Script Capitals": "SVN-HC Matura Script Capitals.otf",
  "SVN HC Newyork Clean": "SVN-HC Newyork Clean.otf",
  "SVN HC Oilvare Base": "SVN-HC Oilvare Base.otf",
  "SVN HC Old Newspaper Types": "SVN-HC Old Newspaper Types.otf",
  "SVN HC Oldstyle Italic": "SVN-HC Oldstyle Italic.otf",
  "SVN HC Organ Grinder": "SVN-HC Organ Grinder.otf",
  "SVN HC Oronteus Finaeus": "SVN-HC Oronteus Finaeus.otf",
  "SVN HC Pacifico": "SVN-HC Pacifico.otf",
  "SVN HC Quotes Caps": "SVN-HC Quotes Caps.otf",
  "SVN HC Quotes Script": "SVN-HC Quotes Script.otf",
  "SVN HC Radiant Bold Cond": "SVN-HC Radiant Bold Cond.otf",
  "SVN HC Read One": "SVN-HC Read One.otf",
  "SVN HC Rostrum": "SVN-HC Rostrum.otf",
  "SVN HC Santoro Script": "SVN-HC Santoro Script.otf",
  "SVN HC Spot": "SVN-HC Spot.otf",
  "SVN HC Spy Royal": "SVN-HC Spy Royal.otf",
  "SVN HC Stay Kool": "SVN-HC Stay Kool.otf",
  "SVN HC Steak And Cheese Condensed": "SVN-HC Steak And Cheese Condensed.otf",
  "SVN HC Steak And Cheese Pen": "SVN-HC Steak And Cheese Pen.otf",
  "SVN HC Steak And Cheese Slab": "SVN-HC Steak And Cheese Slab.otf",
  "SVN HC Strenuous": "SVN-HC Strenuous.otf",
  "SVN HC The Pretender": "SVN-HC The Pretender.otf",
  "SVN HC Transformacio": "SVN-HC Transformacio.otf",
  "SVN HC Velcro": "SVN-HC Velcro.otf",
  "SVN HC Venhille Quaver": "SVN-HC Venhille Quaver.otf",
  "SVN HC Yellowtail": "SVN-HC Yellowtail.otf",
  "SVN HC Yeoman Gothic": "SVN-HC Yeoman Gothic.otf",
  "SVN Headliner No 45": "SVN-Headliner No 45.otf",
  "SVN Heart And Soul Smooth": "SVN-Heart And Soul Smooth.otf",
  "SVN Heart And Soul": "SVN-Heart And Soul Smooth.otf",
  "SVN Heathergreen": "SVN-Heathergreen.otf",
  "SVN Heavenly": "SVN-Heavenly.otf",
  "SVN Heimer": "SVN-Heimer.otf",
  "SVN Helga": "SVN-Helga.otf",
  "SVN Hello Headline": "SVN-Hello Headline.otf",
  "SVN Hello Lucky Ink": "SVN-Hello Lucky Ink.otf",
  "SVN Hello Lucky": "SVN-Hello Lucky Ink.otf",
  "SVN Hello Sunshine Marker": "SVN-Hello Sunshine Marker.otf",
  "SVN Hello Sunshine": "SVN-Hello Sunshine Marker.otf",
  "SVN Hello Sweets": "SVN-Hello Sweets.otf",
  "SVN Heritage": "SVN-Heritage.otf",
  "SVN Heroe Pro Inline": "SVN-Heroe Pro Inline.otf",
  "SVN Heroe Pro Monoline": "SVN-Heroe Pro Monoline.otf",
  "SVN Heroe Pro": "SVN-Heroe Pro Fleurons.otf",
  "SVN Hiro Misake": "SVN-Hiro Misake.otf",
  "SVN Hogfish": "SVN-Hogfish.otf",
  "SVN Holiday": "SVN-Holiday.otf",
  "SVN Hollie Script Pro": "SVN-Hollie Script Pro.ttf",
  "SVN Hollycakes": "SVN-Hollycakes.otf",
  "SVN Hottroof Semhesta": "SVN-Hottroof Semhesta.otf",
  "SVN Housttely Signature": "SVN-Housttely Signature.otf",
  "SVN Hughs": "SVN-Hughs.otf",
  "SVN Ilyas": "SVN-Ilyas.otf",
  "SVN Indie": "SVN-Indie.ttf",
  "SVN Intro Script Base Shade": "SVN-Intro Script Base Shade.otf",
  "SVN Intro Script Base": "SVN-Intro Script Base Shade.otf",
  "SVN Iolanthe": "SVN-Iolanthe.otf",
  "SVN Jane Austen": "SVN-Jane Austen.otf",
  "SVN Janelotus": "SVN-Janelotus.otf",
  "SVN Jealous": "SVN-Jealous.otf",
  "SVN Jonesy Script": "SVN-Jonesy Script.ttf",
  "SVN Jonitha Script": "SVN-Jonitha Script.otf",
  "SVN Journey": "SVN-Journey Ornaments.otf",
  "SVN Just Saying": "SVN-Just Saying Dings.otf",
  "SVN Just Sunday": "SVN-Just Sunday.otf",
  "SVN Justice League": "SVN-Justice League.otf",
  "SVN Karasha": "SVN-Karasha.otf",
  "SVN Karlita": "SVN-Karlita.ttf",
  "SVN Kashima Brush": "SVN-Kashima Brush.otf",
  "SVN Kelso": "SVN-Kelso.otf",
  "SVN KG Broken Vessels Sketch": "SVN-KG Broken Vessels Sketch.otf",
  "SVN Kingtom": "SVN-Kingtom.otf",
  "SVN Kitten": "SVN-Kitten.otf",
  "SVN Koma": "SVN-Koma.ttf",
  "SVN Konfuciuz": "SVN-Konfuciuz.otf",
  "SVN Kontras": "SVN-Kontras.otf",
  "SVN Korean Calligraphy": "SVN-Korean Calligraphy.otf",
  "SVN La Paloma": "SVN-La Paloma.otf",
  "SVN Larch Shaded": "SVN-Larch Shaded.otf",
  "SVN Last Paradise": "SVN-Last Paradise.ttf",
  "SVN Le Beaune New": "SVN-Le Beaune New.otf",
  "SVN Le Murmure": "SVN-Le Murmure.otf",
  "SVN Lemon Tuesday": "SVN-Lemon Tuesday.otf",
  "SVN LeOsler": "SVN-LeOsler.otf",
  "SVN Lifehack Basic": "SVN-Lifehack Basic.ttf",
  "SVN Lifehack Sans": "SVN-Lifehack Sans.ttf",
  "SVN Lifehack Script": "SVN-Lifehack Script.ttf",
  "SVN Little Pea": "SVN-Little Pea.otf",
  "SVN Lolapeluza Black": "SVN-Lolapeluza Black.ttf",
  "SVN Longstride": "SVN-Longstride.otf",
  "SVN Lostar": "SVN-Lostar.otf",
  "SVN Love Potion": "SVN-Love Potion.otf",
  "SVN Lovecure": "SVN-Lovecure.otf",
  "SVN Ludicrous": "SVN-Ludicrous.otf",
  "SVN Lust Script": "SVN-Lust Script.otf",
  "SVN Mabella": "SVN-Mabella.otf",
  "SVN Madre Script": "SVN-Madre Script.ttf",
  "SVN Magnificent": "SVN-Magnificent.otf",
  "SVN Manchester Park": "SVN-Manchester Park.otf",
  "SVN Mangoberry": "SVN-Mangoberry.otf",
  "SVN Manus": "SVN-Manus.otf",
  "SVN Maphylla": "SVN-Maphylla.otf",
  "SVN Marcel Script Pro": "SVN-Marcel Script Pro.ttf",
  "SVN Marpesia Pro": "SVN-Marpesia Pro.ttf",
  "SVN Marujo Fino": "SVN-Marujo Fino.otf",
  "SVN Marujo Pictures": "SVN-Marujo Pictures.otf",
  "SVN Marujo": "SVN-Marujo Fino.otf",
  "SVN Maudy Script": "SVN-Maudy Script.ttf",
  "SVN Megante": "SVN-Megante.otf",
  "SVN Melissa": "SVN-Melissa.ttf",
  "SVN Mercuria": "SVN-Mercuria.otf",
  "SVN Mercury Script Bold": "SVN-Mercury Script Bold.otf",
  "SVN Mercury Script Light": "SVN-Mercury Script Light.otf",
  "SVN Mercury Script Regular": "SVN-Mercury Script Regular.otf",
  "SVN Micheline": "SVN-Micheline.otf",
  "SVN Modern Society": "SVN-Modern Society.otf",
  "SVN Momento": "SVN-Momento.ttf",
  "SVN Moon Earth": "SVN-Moon Earth.otf",
  "SVN MORVA": "SVN-MORVA Ornaments.ttf",
  "SVN MoshiMoshi": "SVN-MoshiMoshi.otf",
  "SVN Mothica": "SVN-Mothica.otf",
  "SVN Mukadua": "SVN-Mukadua.otf",
  "SVN Naive Inline Bold": "SVN-Naive Inline Bold.otf",
  "SVN Nautica": "SVN-Nautica.otf",
  "SVN New Athletic M54": "SVN-New Athletic M54.ttf",
  "SVN Nexa Rust Handmade Extended": "SVN-Nexa Rust Handmade Extended.ttf",
  "SVN Nexa Rust Sans Black": "SVN-Nexa Rust Sans Black.ttf",
  "SVN Nexa Rust Script": "SVN-Nexa Rust Script.ttf",
  "SVN Nexa Rust Slab Black Shadow": "SVN-Nexa Rust Slab Black Shadow.ttf",
  "SVN Nickainley Script": "SVN-Nickainley Script.otf",
  "SVN Night Wind Sent": "SVN-Night Wind Sent.otf",
  "SVN Norse Bold": "SVN-Norse Bold.otf",
  "SVN Norse Regular": "SVN-Norse Regular.otf",
  "SVN Notera": "SVN-Notera.ttf",
  "SVN Nothing": "SVN-Nothing.otf",
  "SVN Notulen Serif Display ExtraBold": "SVN-Notulen Serif Display ExtraBold .otf",
  "SVN Novelia": "SVN-Novelia.ttf",
  "SVN Nubya": "SVN-Nubya.otf",
  "SVN Nuit": "SVN-Nuit.otf",
  "SVN Okami": "SVN-Okami.otf",
  "SVN One Day": "SVN-One Day.otf",
  "SVN Oriental Kaishu": "SVN-Oriental Kaishu.otf",
  "SVN Palaima LC": "SVN-Palaima LC.otf",
  "SVN Palmaton": "SVN-Palmaton.otf",
  "SVN PalmerLakePrint": "SVN-PalmerLakePrint.otf",
  "SVN PalmerLakeScript": "SVN-PalmerLakeScript.otf",
  "SVN Paradise": "SVN-Paradise.otf",
  "SVN Paris Pro": "SVN-Paris Pro.otf",
  "SVN Passion": "SVN-Passion.ttf",
  "SVN Pasternak": "SVN-Pasternak.otf",
  "SVN Pateglamt Script": "SVN-Pateglamt Script.ttf",
  "SVN Pentastic": "SVN-Pentastic.otf",
  "SVN Pequena Neo Black": "SVN-Pequena Neo Black.otf",
  "SVN Pequena Neo Regular": "SVN-Pequena Neo Regular.otf",
  "SVN Pleasent": "SVN-Pleasent.otf",
  "SVN Posterizer KG Inline": "SVN-Posterizer KG Inline.otf",
  "SVN Progs": "SVN-Progs.otf",
  "SVN Pyes Pa Headline": "SVN-Pyes Pa Headline.otf",
  "SVN Qalisha Signature Script": "SVN-Qalisha Signature Script.otf",
  "SVN Qalisha Signature Serif": "SVN-Qalisha Signature Serif.otf",
  "SVN Quarzo": "SVN-Quarzo.otf",
  "SVN Quattrocento Bold": "SVN-Quattrocento Bold.otf",
  "SVN Quattrocento Regular": "SVN-Quattrocento Regular.otf",
  "SVN Radiant Slender": "SVN-Radiant Slender.otf",
  "SVN Rawkstone": "SVN-Rawkstone.otf",
  "SVN Redtowns": "SVN-Redtowns.otf",
  "SVN Reklama CF": "SVN-Reklama CF.otf",
  "SVN Reklame Script": "SVN-Reklame Script.ttf",
  "SVN Retron 2000": "SVN-Retron 2000.otf",
  "SVN RidemyBike Pro Bold": "SVN-RidemyBike Pro Bold.otf",
  "SVN RidemyBike Pro Regular": "SVN-RidemyBike Pro Regular.otf",
  "SVN Ringdena": "SVN-Ringdena.otf",
  "SVN Rio 2016": "SVN-Rio 2016.otf",
  "SVN Risotto Script Pro": "SVN-Risotto Script Pro Extras.ttf",
  "SVN Road Rage": "SVN-Road Rage.otf",
  "SVN Roadbrush": "SVN-Roadbrush.otf",
  "SVN Rockness": "SVN-Rockness.otf",
  "SVN Rohtwo": "SVN-Rohtwo.otf",
  "SVN RollgatesLuxury": "SVN-RollgatesLuxury.otf",
  "SVN Romaji Mincho": "SVN-Romaji Mincho.otf",
  "SVN Rosalinda": "SVN-Rosalinda.ttf",
  "SVN Roselina Script": "SVN-Roselina Script.otf",
  "SVN Rosellinda Alyamore": "SVN-Rosellinda Alyamore.otf",
  "SVN Ruca": "SVN-Ruca.otf",
  "SVN Rush Hour": "SVN-Rush Hour.otf",
  "SVN Rushtick": "SVN-Rushtick.otf",
  "SVN Sablon Washed Super": "SVN-Sablon Washed Super.otf",
  "SVN Safina Script": "SVN-Safina Script.ttf",
  "SVN Sage 2": "SVN-Sage 2.otf",
  "SVN Sage": "SVN-Sage 2.otf",
  "SVN Saint Monica": "SVN-Saint Monica.otf",
  "SVN Saldina": "SVN-Saldina.ttf",
  "SVN Salty Sans": "SVN-Salty Sans.otf",
  "SVN Salty Script": "SVN-Salty Script.otf",
  "SVN Sambay": "SVN-Sambay.otf",
  "SVN Santillana Daughter": "SVN-Santillana Daughter.otf",
  "SVN Santis": "SVN-Santis.ttf",
  "SVN Sarifa": "SVN-Sarifa.otf",
  "SVN Saudagar": "SVN-Saudagar.otf",
  "SVN Saycheez": "SVN-Saycheez.ttf",
  "SVN Secesja Pro": "SVN-Secesja Pro.ttf",
  "SVN Seiston": "SVN-Seiston.otf",
  "SVN Servetica Medium": "SVN-Servetica Medium.otf",
  "SVN Servetica Thin": "SVN-Servetica Thin.otf",
  "SVN Sevillana": "SVN-Sevillana.ttf",
  "SVN Sharpen": "SVN-Sharpen.otf",
  "SVN Shikamaru": "SVN-Shikamaru.otf",
  "SVN Shintia Script": "SVN-Shintia Script.ttf",
  "SVN Showcase Sans": "SVN-Showcase Sans.ttf",
  "SVN Showcase Slab": "SVN-Showcase Slab.ttf",
  "SVN Sign Painter House Script": "SVN-Sign Painter House Script.otf",
  "SVN Signatrue": "SVN-Signatrue.otf",
  "SVN Silver": "SVN-Silver Ornaments.otf",
  "SVN Skill": "SVN-Skill.ttf",
  "SVN Slabrush": "SVN-Slabrush.otf",
  "SVN Slow Attack 2": "SVN-Slow Attack 2.ttf",
  "SVN Slow Attack": "SVN-Slow Attack 2.ttf",
  "SVN Smirk": "SVN-Smirk.otf",
  "SVN Snell Roundhand Script Bold": "SVN-Snell Roundhand Script Bold.ttf",
  "SVN Snell Roundhand Script": "SVN-Snell Roundhand Script Bold.ttf",
  "SVN Space Age": "SVN-Space Age.otf",
  "SVN Spencerio": "SVN-Spencerio.otf",
  "SVN Splandor": "SVN-Splandor.otf",
  "SVN Standly": "SVN-Standly.otf",
  "SVN Steady": "SVN-Steady.otf",
  "SVN Stella": "SVN-Stella.otf",
  "SVN Stereoflows": "SVN-Stereoflows.otf",
  "SVN Stick A Round": "SVN-Stick A Round.ttf",
  "SVN Sticky Toffee Pudding": "SVN-Sticky Toffee Pudding.otf",
  "SVN Stiff Staff": "SVN-Stiff Staff.otf",
  "SVN Stingray": "SVN-Stingray.otf",
  "SVN Storyteller Sans": "SVN-Storyteller Sans.ttf",
  "SVN Storyteller Script": "SVN-Storyteller Script.ttf",
  "SVN Storyteller Serif": "SVN-Storyteller Serif.ttf",
  "SVN Stradas": "SVN-Stradas.otf",
  "SVN Strangelove": "SVN-Strangelove.ttf",
  "SVN Studio Brush": "SVN-Studio Brush.otf",
  "SVN Suargie": "SVN-Suargie.ttf",
  "SVN Sunday": "SVN-Sunday.ttf",
  "SVN Sunflora": "SVN-Sunflora.otf",
  "SVN Sunflower": "SVN-Sunflower.otf",
  "SVN Sunshine": "SVN-Sunshine.ttf",
  "SVN Supercell Magic": "SVN-Supercell Magic.otf",
  "SVN Swashington": "SVN-Swashington.otf",
  "SVN Sweetie": "SVN-Sweetie.otf",
  "SVN Swissquote Medium": "SVN-Swissquote Medium.otf",
  "SVN Swissquote Regular": "SVN-Swissquote Regular.otf",
  "SVN Taken by Vultures": "SVN-Taken by Vultures.otf",
  "SVN Tamarindo": "SVN-Tamarindo.otf",
  "SVN Tangerine": "SVN-Tangerine.otf",
  "SVN Tanglewoods Sans": "SVN-Tanglewoods Sans.otf",
  "SVN Tanglewoods Script": "SVN-Tanglewoods Script.otf",
  "SVN Teaters": "SVN-Teaters.otf",
  "SVN The Carpenter Bold": "SVN-The Carpenter Bold.otf",
  "SVN The Carpenter Regular": "SVN-The Carpenter Regular.otf",
  "SVN The Cats Whiskers": "SVN-The Cats Whiskers.otf",
  "SVN The Secret": "SVN-The Secret.ttf",
  "SVN The Untold Story": "SVN-The Untold Story.otf",
  "SVN The Wild Things Sans": "SVN-The Wild Things Sans.otf",
  "SVN The Wild Things Script": "SVN-The Wild Things Script.otf",
  "SVN Tingler Script": "SVN-Tingler Script.otf",
  "SVN Tioxo Sans": "SVN-Tioxo Sans.otf",
  "SVN Tipper": "SVN-Tipper.otf",
  "SVN TokigPx": "SVN-TokigPx.ttf",
  "SVN Top Secret": "SVN-Top Secret.otf",
  "SVN ToySans": "SVN-ToySans.ttf",
  "SVN TradeMark": "SVN-TradeMark.ttf",
  "SVN Trench": "SVN-Trench.ttf",
  "SVN Truffaux Pro": "SVN-Truffaux Pro.otf",
  "SVN Twilight Script": "SVN-Twilight Script.otf",
  "SVN Uncle Ben": "SVN-Uncle Ben.otf",
  "SVN Unthrift": "SVN-Unthrift.otf",
  "SVN UT Triumph Press": "SVN-UT Triumph Press.otf",
  "SVN UT Triumph Regular": "SVN-UT Triumph Regular.otf",
  "SVN Vala": "SVN-Vala.otf",
  "SVN Vampires": "SVN-Vampires.otf",
  "SVN Vandella": "SVN-Vandella.otf",
  "SVN Vanilla Daisy Pro": "SVN-Vanilla Daisy Pro.ttf",
  "SVN Velvetberries": "SVN-Velvetberries.ttf",
  "SVN Veneer": "SVN-Veneer Extras.ttf",
  "SVN Verveine": "SVN-Verveine.ttf",
  "SVN Very Berry": "SVN-Very Berry.ttf",
  "SVN Victoria": "SVN-Victoria.ttf",
  "SVN Wallington": "SVN-Wallington.ttf",
  "SVN Wallows": "SVN-Wallows Ornaments.otf",
  "SVN Water Bold": "SVN-Water Bold.otf",
  "SVN Water Regular": "SVN-Water Regular.otf",
  "SVN We Youth": "SVN-We Youth.otf",
  "SVN Wednesday": "SVN-Wednesday.otf",
  "SVN Wellfont": "SVN-Wellfont.otf",
  "SVN Wendi": "SVN-Wendi.otf",
  "SVN Woodpecker": "SVN-Woodpecker.otf",
  "SVN Writing Tresno": "SVN-Writing Tresno.otf",
  "SVN Wrong Hunt": "SVN-Wrong Hunt Underline.otf",
  "SVN Wylie Voigen": "SVN-Wylie Voigen.otf",
  "SVN XXII Grober Pinsel": "SVN-XXII Grober Pinsel.ttf",
  "SVN XXII Yeah Script": "SVN-XXII Yeah Script.ttf",
  "SVN Yamet Kudasi": "SVN-Yamet Kudasi.otf",
  "SVN Yipes": "SVN-Yipes.otf",
  "SVN Young Love": "SVN-Young Love.otf",
  "SVN Zailla Script": "SVN-Zailla Script.ttf",
  "SVN Zatiyan": "SVN-Zatiyan.otf",
  "SVN Zelda Sans": "SVN-Zelda Sans.otf",
  "SVN Ziclets": "SVN-Ziclets.ttf",
  "tahoma": "tahoma.ttf",
  "TH Hopeitissed": "TH  Hopeitissed.ttf",
  "UTM A&S Graceland": "UTM A&S Graceland.ttf",
  "UTM A&S Heartbeat": "UTM A&S Heartbeat.ttf",
  "UTM A&S Signwriter": "UTM A&S Signwriter.ttf",
  "UTM Agin": "UTM Agin.ttf",
  "UTM Alpine KT": "UTM Alpine KT.ttf",
  "UTM Aquarelle": "UTM Aquarelle.ttf",
  "UTM Bustamalaka": "UTM Bustamalaka.ttf",
  "UTM Caviar": "UTM Caviar.ttf",
  "UTM Diana": "UTM Diana.ttf",
  "UTM Dinh Tran": "UTM Dinh Tran.ttf",
  "UTM Duepuntozero": "UTM Duepuntozero.ttf",
  "UTM EdwardianB": "UTM EdwardianB.ttf",
  "UTM EdwardianKT": "UTM EdwardianKT.ttf",
  "UTM French Vanilla": "UTM French Vanilla.ttf",
  "UTM Gloria": "UTM Gloria.ttf",
  "UTM Gradoo": "UTM Gradoo.ttf",
  "UTM IsadoraR": "UTM IsadoraR.ttf",
  "UTM LinotypeZapfino KT": "UTM LinotypeZapfino KT.ttf",
  "UTM Neo Sans Intel": "UTM Neo Sans Intel.ttf",
  "UTM Neo Sans IntelBold": "UTM Neo Sans IntelBold.ttf",
  "UTM Neo Sans IntelBold Italic": "UTM Neo Sans IntelBold_Italic.ttf",
  "UTM Neo Sans Intel Italic": "UTM Neo Sans Intel_Italic.ttf",
  "UTM Novido": "UTM Novido.ttf",
  "UTM Pierre": "UTM Pierre.ttf",
  "UTM Sarah": "UTM Sarah.ttf",
  "UTM Scriptina KT": "UTM Scriptina KT.ttf",
  "UTM Silk Script": "UTM Silk Script.ttf",
  "UTM Sloop 1": "UTM Sloop 1.ttf",
  "UTM Soraya": "UTM Soraya.ttf",
  "UTM Spring": "UTM Spring.ttf",
  "UTM Swashes": "UTM Swashes.ttf",
  "UTM ViceroyJF": "UTM ViceroyJF.ttf",
  "UTM Wedding K&T": "UTM Wedding K&T.ttf",
  "UTM Yen Tu": "UTM Yen Tu.ttf",
  "UTM Yves KT": "UTM Yves KT.ttf",
  "UTM Yves KT Bold": "UTM Yves KT_Bold.ttf",
  "UTM Zirkon": "UTM Zirkon.ttf",
  "UVF Kizo": "UVF - Kizo.ttf",
  "UVF LH Line1 Sans Thin": "UVF LH Line1 Sans Thin.ttf",
  "UVNBucThu": "UVNBucThu.TTF",
  "UVNConThuy": "UVNConThuy.TTF",
  "UVNHoaTay1": "UVNHoaTay1.TTF",
  "UVNHuongQue R": "UVNHuongQue_R.TTF",
  "UVNKeChuyen1": "UVNKeChuyen1.TTF",
  "UVNKeChuyen2": "UVNKeChuyen2.TTF",
  "UVNKeChuyen3": "UVNKeChuyen3.TTF",
  "UVNKieu R": "UVNKieu_R.TTF",
  "UVNLYDO": "UVNLYDO.TTF",
  "UVNMauTim1": "UVNMauTim1.TTF",
  "UVNMauTim2": "UVNMauTim2.TTF",
  "UVNMuaThu": "UVNMuaThu.TTF",
  "UVNSangSong R": "UVNSangSong_R.TTF",
  "UVNThoiDai1": "UVNThoiDai1.TTF",
  "UVNThuTu": "UVNThuTu.TTF",
  "zitroneFY": "zitroneFY.otf"
};